//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCleanB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.SanPhamGioHangs = new HashSet<SanPhamGioHang>();
        }
    
        public int MaHang { get; set; }
        public System.Guid MaNhaCungCap { get; set; }
        public int MaNhomHang { get; set; }
        public Nullable<System.Guid> Sku { get; set; }
        public string TenHang { get; set; }
        public string MoTa { get; set; }
        public decimal GiaThanh { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> KhoiLuong { get; set; }
        public Nullable<decimal> TheTich { get; set; }
        public Nullable<decimal> KhuyenMai { get; set; }
        public string AnhSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhomHang NhomHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamGioHang> SanPhamGioHangs { get; set; }
    }
}
